### ISSUE TITLE
Issue with Card SCAN SDK in iOS Sandbox Environment

### ISSUE THREAD

**Issue by mfsi-waseema** [CardScan-ai/insurance-card-scan-ios#1]
The problem we are encountering is that the Card SCAN SDK appears to be consistently calling the production API instead of the Sandbox API, as indicated by the error logs.

CS _get:  https://api.cardscan.ai/v1/generate-upload-url
CS generate-upload-url: json parsing error - %@ ["code": 401, "message": Token was not issued for this resource, "type": Unauthorized]

**Comment by nickls** [comment]
hi @mfsi-waseema  -- thanks for creating an issue.

You'll need to initialize the `CardScanViewController` object to use sandbox mode before it will contact the correct server. 

You can do this by setting the argument `live` to be `false`:
```
    let cardScannerViewController = CardScannerViewController(sessionToken: sessionToken, live: false)
```

You can read more on our documentation here:
https://docs.cardscan.ai/ui-components/ios

**Comment by mfsi-waseema** [comment]
We are doing same.
    let cardScannerViewController = CardScannerViewController(userToken: sessionToken, live: false)

      cardScannerViewController.present(from: self, animated:true) { result in
        print(result)
          switch result {
          case .success(let card):
              print(card)
              //prepopulate UI and push results to server.
          case .failure(let error):
              //log and handle errors
              print(error)
          case .canceled:
              print("User canceled -- update UI to refect this.")
          @unknown default:
              print("Unknown cardscan result")
          }
      }

But always getting error.
====
Errors found! Invalidating cache...
2023-07-24 16:28:13.868693+0530 Demo[4654:202530] Errors found! Invalidating cache...
CardScan: didFinishRecognization with success
CS _get:  https://api.cardscan.ai/v1/generate-upload-url
CS generate-upload-url: json parsing error - %@ ["code": 401, "type": Unauthorized, "message": Token was not issued for this resource]
CardScan: uploadCardImage error invalidJSONResponse

**Comment by nickls** [comment]
fixed in latest
